[tool.poetry]
name = "ps2"
version = "0.1.0"
description = ""
authors = ["Rulrn <rulrnovistky@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.26"
matplotlib = "^3.8.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
